spring:
  application:
    name: currency-converter-service  http:    encoding:      force: false
      enabled: false  boot:    admin:      client:        url:        - http://localhost:9999  security:    user:      name: root
      password: root
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
          defaultZone: http://localhost:8070/eureka/      
server:  port: 9019

#currency-exchange-service:
    #ribbon:
        # listOfServers: localhost:8093,localhost:8092
         #ServerListRefreshInterval: 150
   

                    